const express = require("express")
const router = express.Router()
const {Login,Register,Logout} = require("../controller/user.controller")
const {GetListApplicants,GetSpecifyApplicants,DeleteApplicants} = require("../controller/applicants.controller")
const {GetVacancyLimited,GetSpecifyVacancy,AddVacancy,GetAllVacancy} = require("../controller/vacancy.controller") 
const {ApplyJob} = require("../controller/apply.job.controller")
const {UserAuth} = require("../middleware/jwt")
router.post("/login",Login)
router.post("/register",Register)
router.get("/logout",Logout)
router.get("/dashboard",UserAuth,GetListApplicants)
router.delete("/dashboard",DeleteApplicants)
router.get('/applicants/:id',UserAuth,GetSpecifyApplicants)
router.get("/view",GetVacancyLimited)
router.post("/add-vacancy",UserAuth,AddVacancy)
router.get("/view/:id",GetSpecifyVacancy)
router.post("/view/:id",ApplyJob)
router.get("/search",GetAllVacancy)
router.get("/search/:id",GetSpecifyVacancy)
router.post("/search/:id",ApplyJob)
module.exports = router

